x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      A regular update.
    releaseTypes:
      - Feature
    recommended: false

  managedUpdates:
    kalmSupported: false

  images:
    '':
      properties:
        image.repo:
          type: REPO_WITH_REGISTRY
        image.tag:
          type: TAG
    prometheus-to-sd:
      properties:
        metrics.image:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  certificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: nginx.tls.base64EncodedPrivateKey
          base64EncodedCertificate: nginx.tls.base64EncodedCertificate

required:
- name
- namespace
