apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "click-to-deploy-containers", "product_id": {{ .Chart.Name | quote }}, "partner_name": "Google Click to Deploy"}'
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  descriptor:
    type: Neo4j
    version: "{{ .Values.image.tag }}"
    description: |-
      Descricao
    maintainers:
    - name: Google Click to Deploy
      url: https://cloud.google.com/solutions/#click-to-deploy
    links:
    - description: 'User Guide: Google Click to Deploy Neo4j Community'
      url: https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/neo4j-ce/README.md
    - description: 'Getting started with Neo4j'
      url: https://neo4j.com/developer/get-started/
    - description: Neo4j 4.x Reference Manual
      url: https://neo4j.com/docs/
    - description: Neo4j Code Samples Repository
      url: https://github.com/neo4j-examples

    notes: |-
      Notas

  info:
  - name: Neo4j Browser (local only)
    value: http://localhost:7474/browser/

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: Secret
  - group: v1
    kind: Service
  - group: apps/v1
    kind: StatefulSet
  - group: v1
    kind: PersistentVolumeClaim
