# Main chart attributes

image:
  repo: gcr.io/orbitera-dev/laravel7:7.3
  tag: '7.3'
persistence:
  size: 10Gi
  storageClass: standard
metrics:
  exporter:
    enabled: false
    image: null

# Sub-charts attributes

nginx:
  image:
    repo: marketplace.gcr.io/google/nginx
    tag: 1.15
  replicas: 3
  initImage: marketplace.gcr.io/google/nginx/debian9:1.15
  metrics:
    exporter:
      enabled: true
    image: marketplace.gcr.io/google/nginx/prometheus-to-sd:1.15
    curatedExporter:
      enabled: false

enablePublicServiceAndIngress: true
