---
# Source: laravel-stack/charts/nginx/templates/nginx-statefulset.yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: laravel-1-nginx
  labels: &NginxDeploymentLabels
    app.kubernetes.io/name: laravel-1
    app.kubernetes.io/component: nginx-server
spec:
  selector:
    matchLabels: *NginxDeploymentLabels
  updateStrategy:
    type: RollingUpdate
  serviceName: laravel-1-nginx-svc
  replicas: 3
  volumeClaimTemplates:
  - metadata:
      name: laravel-1-nginx-pvc
      labels: *NginxDeploymentLabels
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels: *NginxDeploymentLabels
    spec:
      terminationGracePeriodSeconds: 180
      initContainers:
      # This init container is reponsible for creating default index html file
      - name: initialize-volume
        image: marketplace.gcr.io/google/nginx/debian9:1.15
        imagePullPolicy: Always
        command:
        - /bin/bash
        - -euc
        - |
          if [[ ! -f /usr/share/nginx/html/index.html ]]; then
          cat <<EOF >/usr/share/nginx/html/index.html
          <!DOCTYPE>
          <html>
            <head>
              <title>Web Server Application</title>
            </head>
            <body>
               <h1>Web site powered by NGINX</h1>
               <p>This page is under construction. Please come back soon!</p>
            </body>
          </html>
          EOF
          fi
        volumeMounts:
        - name: laravel-1-nginx-pvc
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: "marketplace.gcr.io/google/nginx:1.15"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: nginx
          containerPort: 80
          protocol: TCP
        - name: nginx-https
          containerPort: 443
          protocol: TCP
        - name: prometheus
          containerPort: 9113
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: nginx
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: nginx
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: laravel-1-nginx-pvc
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: certs
          mountPath: /etc/nginx/certs
          readOnly: true
      
      
      volumes:
      - name: certs
        secret:
          secretName: laravel-1-nginx-secret
      - name: nginx-config
        configMap:
          name: laravel-1-nginx-configmap
          items:
          - key: nginx-config.conf
            path: nginx-config.conf
