---
# Source: laravel-stack/charts/nginx/templates/nginx-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: laravel-1-nginx-secret
  labels:
    app.kubernetes.io/name: laravel-1
    app.kubernetes.io/component: nginx-server
data:
  https1.cert: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lVVTlnY2xYS1F2
    V2tacnZ2NTAxRi9kTmM5eFd3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lERU9NQXdHQTFVRUF3d0Zi
    bWRwYm5neERqQU1CZ05WQkFvTUJXNW5hVzU0TUI0WERUSXdNRFF4TVRBMQpNemt3TWxvWERUSXhN
    RFF4TVRBMU16a3dNbG93SURFT01Bd0dBMVVFQXd3RmJtZHBibmd4RGpBTUJnTlZCQW9NCkJXNW5h
    VzU0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwZzdwWTY0VlNo
    d2sKWnFnUC9pQXlGU2NDYngydGpSUUVncFpTRzZIbUFlc1hOTU9ydStSVHpyQXJ5b1lZOEN2RE5G
    WGxrU21FNHF3SwpXdkhBRjBlS3pRRzJ5eGRWMVU2SnlCR2Mwa0pTZGFkQlpIYVU5dzF5end1aUda
    Y1Mxa2Z4enFpNTY0RjFHYW02ClV3a0lJd1pFTGVXYXZESkpwVVhvRHlwV2MrN0N5WERiM3dNSUpu
    UnhNTzl1SFl6eEtQWE1xWDJ3REpjTEtvMlUKMndiOUJBS2Z6VmVZbERiVFhxK3F2VWdqbHRvK3dH
    ZFpMNWdoWndDRnB3UzRFSWp6MlRPWGQ5K25jdHJCYXVMWgpzZGxWbW40K3Z1ckxxOXlURnRMd3dv
    Tlk1TmFMcHJBZmJYNFl1bmF4U0FwTW5lKzVjZEJJc2ljOVc5dDhpYnRWCmo0aC9yZHZ4VndJREFR
    QUJvMU13VVRBZEJnTlZIUTRFRmdRVW80Z2M0ZjZNcXBOenRJaTFGZlhuUkRpbnMxb3cKSHdZRFZS
    MGpCQmd3Rm9BVW80Z2M0ZjZNcXBOenRJaTFGZlhuUkRpbnMxb3dEd1lEVlIwVEFRSC9CQVV3QXdF
    QgovekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBeUNsSGVMUDhPQldrN3ZUeXA3WnhQSHBXZjM3
    WGFDS2k1bE1TCnJZNFNhOW9hTUpXYVArL1p4RDRoTWVmYzRUamx2OU1Oak5pN0t1NDBYS0tEMWpU
    MEVvUWd4NUNScE5ZdVBJQjEKVnZ2MC9FT000M1hJMi9YYmpGQjlSbjJtNkJ1VnBKV29tdkdRdzlp
    RGtMa05LYmROVGhHMHVzeFlYNE4rckMvWApud3VNbkFrOXh0b1NKcTMwSVB0STFDZStvbk9wb1lo
    aFRnMlROUEd3SkRxWU1RcGhFd2NCWnFBbHk2YkxDMmMyCjh6cDhFZlB6dWR5ZjdnUFBrQm95eExs
    ckU5RXVQRThpTU55d0Y5elZ5NURmRmhyRmQxYzFtRnNha3QwUVE4cFUKVWRJY2RQaFBodURnTndy
    SW1qR2Vxby90QVZNRjNwTGM2VTllaUdWME1SajBscFNKQlE9PQotLS0tLUVORCBDRVJUSUZJQ0FU
    RS0tLS0tCg==
  https1.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktnd2dnU2tBZ0VBQW9JQkFRRFNEdWxqcmhWS0hDUm0KcUEvK0lESVZKd0p2SGEyTkZBU0Ns
    bElib2VZQjZ4YzB3NnU3NUZQT3NDdktoaGp3SzhNMFZlV1JLWVRpckFwYQo4Y0FYUjRyTkFiYkxG
    MVhWVG9uSUVaelNRbEoxcDBGa2RwVDNEWExQQzZJWmx4TFdSL0hPcUxucmdYVVpxYnBUCkNRZ2pC
    a1F0NVpxOE1rbWxSZWdQS2xaejdzTEpjTnZmQXdnbWRIRXc3MjRkalBFbzljeXBmYkFNbHdzcWpa
    VGIKQnYwRUFwL05WNWlVTnROZXI2cTlTQ09XMmo3QVoxa3ZtQ0ZuQUlXbkJMZ1FpUFBaTTVkMzM2
    ZHkyc0ZxNHRteAoyVldhZmo2KzZzdXIzSk1XMHZEQ2cxamsxb3Vtc0I5dGZoaTZkckZJQ2t5ZDc3
    bHgwRWl5SnoxYjIzeUp1MVdQCmlIK3QyL0ZYQWdNQkFBRUNnZ0VCQUlkSEx5c1F5NGtrd3BTU0cy
    cVBsWEZsNC8xbllZTi9wci9xeXdvY282SU0Kb3E5S2JHamV6TkpKUm9wdy9kSitmSUpSNXp3clB2
    Y3owSjl0SFVaZ3ZwVDBTNkpUYnVXbVpMbENEbnFpVjdTSgplR1dZc0tyQ01IUUNpK3hyREtpUFFM
    elVrSmVJa2I5clBTR0lxWUxVNEVlbW5KWWkxS2JwZEY5LzVwbFc1SDhSClVmWFFTUGViWEpWVkkw
    ck92eGdML0hRL29MSHBLRGtJRnVQbVFzTUt3U3Jyb3BZRGRKSmhGRTh0VitSWWhFREkKUWlmSVdB
    OFdFVFQvMmR3bUxFVEhsb0xIaHVabXhvVXlsUU9ZUlVXQkVOU2dKSURSRFo0MG94V3ltOEppSTZp
    VQp6Q0V3eERXbGhDQ3R2Q0UrVUNaQ0RVa0tvTnc1MGRLWEl3SUdhYmVCOUFFQ2dZRUErOGQzTEx1
    aGxRR3FkQU85CnVpWVp4Y1pTMERiL0d1Z3dDcVRtYTRHemRlU2d4cGlNRndqdnZBVkRBdW5ZYUZL
    dms4d3NJQ2lxbmNKeTRYMjIKZ0pLdHp3eE12S0k3ak4xcEtuVXhJTENNZk1ydGU1YzBRNEhxVWhh
    bWw1a2RYajFpYkdTZjdKRjJHa2pxdHJUNgpZbHEzdllvVTFRT0pVQUpvVkdOUkhXVVJPUUVDZ1lF
    QTFaUmxsMXozMVl0M2NDS3pnaUlzMUF1RzJIOTI1N0dSCmN1VlEySDNaRkZxeElrR0JOVEptOWJG
    Tk5CTTdnVEEvUVpqaFROdjlMWmRKK0JSTHVKeEF5VVJqL3g5ajZtVnAKZ3p5Z0FEcjZMS3ZSQU82
    d3NOUDgrdHBENGovb2pIRG9LS1VBRHRaTGd4bkFiL3VOYmhBVlBBNVJnRnZ4cS9aSAp6RWxvTUR0
    L2tsY0NnWUJoZVV0dUNnWDRSZmpUaVU4K2JkbTBjNTlEOU1hMmlBVnhXWDNMU1I5TkdRSVZZS0Y3
    Cm1YNFdjSU1NOGJOU1VCQ2hTMzRaeFNTb2hzc3ErUnhha202dnBiZGZuLzhsL2VIbENoSEc4aEt4
    alc1N1ZvSnAKVURhREtUbTludzE3bXBBc0hwaTdZV1V6cjk4T2RPb3FnYXg0dUtodi96cDl1ekRn
    MnNKZ2V1dzhBUUtCZ0RWNwphcEVqbzUvaXc2N2QwYXVsbVNva0ZNbEQ2ZWVNN0lvajZFRytDY3p5
    Qk9jNkZmdlhPamNPQmZJaldzUTM2NjhtCmRFeUZ6ZmxMcUNjcUZlZ05vSitGczdDZ0VLb1NhUUNH
    L3QzdjV0T20xcmh3RE9qS3ZNK29ObFdDZ1Y0aHE5RDUKdUhEK3Nud0t4OGlDNm1DRVFIMEFiT0pD
    bzlyVzJoWEt6Lzg3OXU4VEFvR0JBTGhiQkQ0d2w2WHd4dVRMSnladwprbHV6L0FPRVZsczVlUVJr
    SUV4bkN5SHF2emdna1JpeUdhV0xTUGNxbUEzVlBZdDFvRy9SM1BmbXNaa3RCL3hvCmFUVXpUYzNy
    ejN4T21XeGNNSy9uZy9oYjUxbGV2V1hGWitXcU5LbDFiMExwUVA1SHc3dE5zVE9xL2NKVVVKVUIK
    QUcrL1BFTk5DRHV3cHlHVXZ4OFJveG4zCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
