---
# Source: laravel-stack/charts/nginx/templates/nginx-services.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-1-nginx-prometheus-svc
  labels:
    app.kubernetes.io/name: laravel-1
    app.kubernetes.io/component: nginx-server
spec:
  clusterIP: None
  ports:
  - name: prometheus-port
    port: 9113
    protocol: TCP
  selector:
    app.kubernetes.io/name: laravel-1
    app.kubernetes.io/component: nginx-server
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-1-nginx-svc
  labels:
    app.kubernetes.io/name: laravel-1
    app.kubernetes.io/component: nginx-server
spec:
  ports:
  - name: nginx-http-port
    port: 80
    protocol: TCP
  - name: nginx-https-port
    port: 443
    protocol: TCP
  selector:
    app.kubernetes.io/name: laravel-1
    app.kubernetes.io/component: nginx-server
  
  type: LoadBalancer
  
